name: my_quotation_generator
description: "A new Flutter project."


publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: ^3.9.2







dependencies:
  flutter:
    sdk: flutter

  #--------------- STATE MANAGEMENT ---------------#
  flutter_riverpod: ^3.0.3
  equatable: ^2.0.7
  get_it: ^8.2.0
  dartz: ^0.10.1
  path_provider: ^2.1.5
  intl: ^0.20.2
  dio: ^5.9.0
  #--------------- STATE MANAGEMENT END ---------------#



  #--------------- DATA BASE --------------------------#
  sqflite: ^2.4.2
  sqlite3_flutter_libs: ^0.5.40
  #--------------- DATA BASE END -----------------------#



  #--------------- PDF + File Sharing -----------------#
  pdf: ^3.11.3
  printing: ^5.14.2
  share_plus: ^12.0.0
  open_filex: ^4.7.0
  #---------------- PDF + File Sharing End -------------#

  #------------------ UI Helpers ---------------------- #
  flutter_svg: ^2.2.1
  google_fonts: ^6.3.2
  #-------------------- UI Helper End -------------------#

  
  
  cupertino_icons: ^1.0.8
  sqflite_common_ffi: ^2.3.6
  go_router: ^16.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^5.0.0





flutter:
  uses-material-design: true
