name: my_quotation_generator
description: A clean architecture Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # ------------------------------------------------------------------
  # STATE MANAGEMENT / CORE
  # ------------------------------------------------------------------
  flutter_riverpod: ^3.0.3
  equatable: ^2.0.7
  get_it: ^9.0.5
  dartz: ^0.10.1

  # ------------------------------------------------------------------
  # NETWORK + REQUESTS
  # ------------------------------------------------------------------
  dio: ^5.9.0

  # ------------------------------------------------------------------
  # FILE SYSTEM & PATH UTILITIES
  # ------------------------------------------------------------------
  path_provider: ^2.1.5
  file_picker: ^10.3.6
  permission_handler: ^12.0.1
  saf: ^1.0.4

  # ------------------------------------------------------------------
  # DATABASE
  # ------------------------------------------------------------------
  sqflite: ^2.4.2
  sqlite3_flutter_libs: ^0.5.40
  sqflite_common_ffi: 2.3.6

  # ------------------------------------------------------------------
  # PDF / SHARING / FILE EXPORT
  # ------------------------------------------------------------------
  pdf: ^3.11.3
  printing: ^5.14.2
  share_plus: ^12.0.0
  open_filex: ^4.7.0
  flutter_pdfview: ^1.3.2


  # ------------------------------------------------------------------
  # UI / STYLING / ROUTING
  # ------------------------------------------------------------------
  flutter_svg: ^2.2.2
  google_fonts: ^6.3.2
  go_router: ^17.0.0

  # ------------------------------------------------------------------
  # CONTACTS / MISC UTILITIES
  # ------------------------------------------------------------------
  flutter_contacts: ^1.1.9+2
  intl: ^0.20.2

  # ------------------------------------------------------------------
  # TESTING UTILITIES
  # ------------------------------------------------------------------
  mocktail: ^1.0.4

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/NotoSans-Regular.ttf
    - assets/fonts/NotoSans-Bold.ttf
